title = "Python Text Tetris"
theme = 'light'
height = 10
width = 20
default_cursor = (0, 10)
left_key = "Left"
right_key = "Right"
down_key = "Down"
up_key = "Up"
left_offset = 1
right_offset = 1
down_offset = 1
end_game_message = "You Have beaten the game!"
levels_dict = {}
levels_dict["level3"]=(30, 3, 20)
levels_dict["level2"]=(20, 2, 10)
levels_dict["level1"]=(10, 1, 5)
difficulty = "easy"
pause_key = "p"
custom_range = range(1, 2)
quit_key = "q"
max_level = 3
rotate_counter_limit = 3
