Someothername=10  
Somename=0  
max_level=3  
pause_key="p"  
difficulty="easy"  
levels_dict["level3"]=(30, 3, 20)
levels_dict["level2"]=(20, 2, 10)
levels_dict["level1"]=(10, 1, 5)
end_game_message="You Have beaten the game!"  
quit_key="q"  
custom_range=range(1, 10)
freq_dist="uniform"  
down_offset=1  
right_offset=1  
left_offset=1  
display_next=1  
up_key="Up"  
down_key="Down"  
right_key="Right"  
left_key="Left"  
default_cursor=(0, 10)
width=20  
height=10  
title="Python Text Tetris"  
